spring.application.name=sras
server.port=8081

# Database URL (replace 'your_database_name' with your actual DB name)
spring.datasource.url=jdbc:mysql://localhost:3306/softbridge?createDatabaseIfNotExist=true

# Database credentials
spring.datasource.username=root
spring.datasource.password=yourRealPassword

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
